### PR TITLE
Fix `no_std` and add CI check

### PR DESCRIPTION
**Pull request by pinkforest**
As is established standard in [curve25519-dalek](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/.github/workflows/workspace.yml#L60) and [fiat-crypto](https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/rust.yml#L34)

### CODE REVIEW

**Comment by pinkforest** [comment]
@bwesterb I fixed Cargo manifest to make sure it doesn't break no_std and uses the resolver that is used by default with workspaces which we're used to - but this crate didn't use workspace so it was implicitly using resolver ="1" that caused it to bring getrandom even when only building - which broke no_std support.

It seems kyber1024 feature is broken - I'll mark it ignored for now
- https://github.com/bwesterb/argyle-kyber/issues/3

**Comment by bwesterb** [comment]
Thanks for this, and please accept my apologies for the late review. I saw it, and then completely forgot about it.

**Comment by bwesterb** [comment]
Had to revert because of build failure

```
error: `#[panic_handler]` function required, but not found

error: unwinding panics are not supported without std
```

**Comment by bwesterb** [comment]
Removing all `panic!` didn't work. Probably some panics in dependency?

**Pull request merged**
